#ifndef _ERROR_H
#define _ERROR_H

#define OK 0

#define NOTENOUGHPOP -1
#define ARETHMETICOVERFLOW -2
#define UNDERFLOW -3
#define NOTDIVIDEZERO -4
#define STACKISFULL -5
#define NOTEVENENOUGHFORTOP -6
#define NOTABLETOUSECALC -8

#endif